--DDL 
--CRIAR BANCO DE DADOS
CREATE DATABASE Exercicio_1_3

--CRIAR TABELAS
CREATE TABLE Clinica
(
	IdClinica INT PRIMARY KEY IDENTITY,
	Endereco VARCHAR(20)NOT NULL,
)

CREATE TABLE Dono
(
	IdDono INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20)NOT NULL
)

CREATE TABLE Raca
(
	IdRaca INT PRIMARY KEY IDENTITY,
	Descricao VARCHAR(20)NOT NULL
)

CREATE TABLE TipoPet
(
	IdTipoPet INT PRIMARY KEY IDENTITY,
	Descricao VARCHAR(20)NOT NULL
)

CREATE TABLE Pet
(
	IdPet INT PRIMARY KEY IDENTITY,
	IdDono INT FOREIGN KEY REFERENCES Dono(IdDono)NOT NULL,
	IdRaca INT FOREIGN KEY REFERENCES Raca(IdRaca)NOT NULL,
	IdTipoPet INT FOREIGN KEY REFERENCES TipoPet(IdTipoPet)NOT NULL,
	Nome VARCHAR(20)NOT NULL,
	Nascimento VARCHAR(20)NOT NULL
)

CREATE TABLE Atendimento
(
	Atendimento INT PRIMARY KEY IDENTITY,
	IdVeterinario INT FOREIGN KEY REFERENCES Veterinario(IdVeterinario)NOT NULL,
	IdPet INT FOREIGN KEY REFERENCES Pet(IdPet)NOT NULL,
	Descricao VARCHAR(20)NOT NULL,
	Protocolo VARCHAR(20)NOT NULL
)

SELECT * FROM Atendimento;

CREATE TABLE Veterinario
(
	IdVeterinario INT PRIMARY KEY IDENTITY,
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica) NOT NULL,
	Nome VARCHAR(20)NOT NULL
)